import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Box,
  AppBar,
  Typography,
  Toolbar,
  IconButton,
  Card,
  Button,
  Paper,
  Container,
  Grid,
} from "@mui/material";
import Main from "../Components/layout/Main";
import Store from "../Components/layout/Store";
import Cancel from "../Components/layout/Cancel";
import Success from "../Components/layout/Success";
import Navbar from "../Components/layoutComponents/Navbar";

const Home: NextPage = () => {
  const router = useRouter();

  const [cartCount, setCartCount] = React.useState<number>(0);

  let { slug } = router.query;
  let page = "";
  // @ts-ignore
  if (slug) {
    page = slug[0];
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar cartCount={cartCount} />

      <Container>
        {page == "store" ? (
          <Store />
        ) : (page == "cancel") === true ? (
          <Cancel />
        ) : (page == "success") === true ? (
          <Success />
        ) : (
          <Store />
        )}
      </Container>
    </>
  );
};

export default Home;
